export function generateAgentUnit(): string {
  return [
    '[Unit]',
    'Description=Fleet Secrets Agent for %i',
    'After=network.target',
    'PartOf=docker-%i.service',
    '',
    '[Service]',
    'Type=notify',
    'DynamicUser=yes',
    'RuntimeDirectory=fleet-secrets',
    'RuntimeDirectoryPreserve=yes',
    'LoadCredentialEncrypted=age-key:/etc/fleet/credentials/%i.cred',
    'ExecStart=/usr/local/bin/fleet-agent --app %i --vault /home/matt/fleet/vault --socket /run/fleet-secrets/%i.sock',
    'Restart=on-failure',
    'RestartSec=2',
    '',
    '# hardening',
    'ProtectSystem=strict',
    'ProtectHome=read-only',
    'ReadOnlyPaths=/home/matt/fleet/vault',
    'PrivateTmp=yes',
    'NoNewPrivileges=yes',
    'ProtectKernelTunables=yes',
    'ProtectKernelModules=yes',
    'ProtectControlGroups=yes',
    'RestrictAddressFamilies=AF_UNIX',
    'RestrictNamespaces=yes',
    'SystemCallFilter=@system-service',
    'SystemCallFilter=~@privileged @resources @mount',
    '',
    '[Install]',
    'WantedBy=multi-user.target',
    '',
  ].join('\n');
}
