/**
 * Log policy: per-app retention/size/level configuration. Materialises as a
 * compose override file (.fleet/logging.override.yml) per app, plus journald
 * vacuum policy. Conservative defaults applied when unset.
 */

import { existsSync, mkdirSync, writeFileSync, readFileSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { execSafe } from './exec';
import { redactText, type RedactionConfig, type RedactionUserConfig } from './redaction';
import type { AppEntry } from './registry';

export interface LogPolicy {
  retentionDays: number;
  maxSizeMB: number;
  level: 'debug' | 'info' | 'warn' | 'error';
}

export const DEFAULT_POLICY: LogPolicy = {
  retentionDays: 7,
  maxSizeMB: 100,
  level: 'info',
};

export function effectivePolicy(app: AppEntry): LogPolicy {
  return {
    retentionDays: app.logging?.retentionDays ?? DEFAULT_POLICY.retentionDays,
    maxSizeMB: app.logging?.maxSizeMB ?? DEFAULT_POLICY.maxSizeMB,
    level: app.logging?.level ?? DEFAULT_POLICY.level,
  };
}

/**
 * Build a docker-compose override that sets json-file driver with rotation.
 * Maps each container to logging.driver/options. Idempotent — overwrites the
 * single override file completely.
 */
export function buildComposeOverride(app: AppEntry, policy: LogPolicy): string {
  const maxSize = `${policy.maxSizeMB}m`;
  const maxFile = '3';
  const services: Record<string, unknown> = {};
  for (const ct of app.containers) {
    services[ct] = {
      logging: {
        driver: 'json-file',
        options: { 'max-size': maxSize, 'max-file': maxFile },
      },
    };
  }
  // Tiny YAML emitter — avoids pulling in a yaml dep for two levels of nesting.
  const lines: string[] = ['# Auto-generated by `fleet logs setup`. Do not edit.', 'services:'];
  for (const [name, cfg] of Object.entries(services)) {
    lines.push(`  ${name}:`);
    lines.push(`    logging:`);
    lines.push(`      driver: json-file`);
    lines.push(`      options:`);
    lines.push(`        max-size: "${(cfg as any).logging.options['max-size']}"`);
    lines.push(`        max-file: "${(cfg as any).logging.options['max-file']}"`);
  }
  return lines.join('\n') + '\n';
}

export function overridePath(app: AppEntry): string {
  return join(app.composePath, '.fleet', 'logging.override.yml');
}

/** ensure the app repo's .gitignore covers .fleet/ so the auto-generated
 *  override file doesn't get committed accidentally. no-op when there's no
 *  .gitignore (operator may be using a different vcs or none at all) and
 *  idempotent — never appends a duplicate entry. */
export function ensureFleetGitignored(composePath: string): void {
  const giPath = join(composePath, '.gitignore');
  if (!existsSync(giPath)) return;
  const current = readFileSync(giPath, 'utf-8');
  // accept any of: .fleet, .fleet/, /.fleet, /.fleet/ — operators write all
  // four forms.
  if (/^\s*\/?\.fleet\/?\s*$/m.test(current)) return;
  const append = current.endsWith('\n') ? '' : '\n';
  writeFileSync(giPath, `${current}${append}\n# auto-added by fleet logs setup\n.fleet/\n`);
}

export function writeComposeOverride(app: AppEntry, policy: LogPolicy): string {
  const path = overridePath(app);
  const dir = dirname(path);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  writeFileSync(path, buildComposeOverride(app, policy));
  // the override lands inside the operator's app repo. add .fleet/ to the
  // app's .gitignore (if there is one) so it doesn't get committed.
  ensureFleetGitignored(app.composePath);
  return path;
}

export interface LogStatus {
  app: string;
  container: string;
  driver: string;
  totalBytes: number | null;
  oldestEntry: string | null;
  policyApplied: boolean;
}

/** Best-effort docker-side log status. Uses `docker inspect` for driver + size. */
export function getLogStatus(app: AppEntry): LogStatus[] {
  const override = overridePath(app);
  const policyApplied = existsSync(override);
  const out: LogStatus[] = [];
  for (const ct of app.containers) {
    const inspect = execSafe('docker', ['inspect', '--format={{.HostConfig.LogConfig.Type}}|{{.LogPath}}', ct]);
    if (!inspect.ok) {
      out.push({ app: app.name, container: ct, driver: 'unknown', totalBytes: null, oldestEntry: null, policyApplied });
      continue;
    }
    const [driver, logPath] = inspect.stdout.trim().split('|');
    let totalBytes: number | null = null;
    if (logPath && existsSync(logPath)) {
      try { totalBytes = statSync(logPath).size; } catch { /* ignore */ }
    }
    out.push({ app: app.name, container: ct, driver, totalBytes, oldestEntry: null, policyApplied });
  }
  return out;
}

/**
 * Vacuum: for json-file driver with rotation already configured, docker
 * handles size automatically. We expose a manual prune that:
 * 1. Truncates the active log file (leaves rotated .1, .2 alone — those age out naturally)
 * 2. For journald-driven containers, runs `journalctl --vacuum-time=Xd` scoped to the unit
 *
 * Returns bytes freed (approximate).
 */
export function pruneLogs(app: AppEntry, policy: LogPolicy): number {
  let freed = 0;
  const status = getLogStatus(app);
  for (const s of status) {
    if (s.driver === 'json-file' && s.totalBytes && s.totalBytes > 0) {
      // Use docker to "logs --truncate" — actually no such cmd. Use docker stop + log file truncate? Risky.
      // Safest: skip active truncation; let docker rotation handle it. Just report.
      // We DO truncate via writing 0-length only if the file is over 5x the policy max
      // (which means rotation isn't catching up — clear it manually).
      const maxBytes = policy.maxSizeMB * 1024 * 1024;
      if (s.totalBytes > maxBytes * 5) {
        try {
          const inspect = execSafe('docker', ['inspect', '--format={{.LogPath}}', s.container]);
          const path = inspect.stdout.trim();
          if (path) {
            const beforeSize = s.totalBytes;
            writeFileSync(path, '');
            freed += beforeSize;
          }
        } catch { /* ignore */ }
      }
    }
  }
  // Journald scope: vacuum by time, scoped to relevant units (best-effort).
  execSafe('journalctl', ['--vacuum-time', `${policy.retentionDays}d`]);
  return freed;
}

/**
 * Read a slice of container logs with bounded options. Used by enhanced
 * `fleet logs` and the MCP tool.
 */
export interface LogReadOpts {
  lines?: number;       // tail N lines
  level?: 'debug' | 'info' | 'warn' | 'error';
  sinceMinutes?: number;
  grep?: string;
  maxBytes?: number;    // hard cap on returned text
  /** Redaction config. Omit for the built-in defaults (redaction ON); pass an
   *  effectiveRedaction(app) result for per-app config, or a config with
   *  enabled:false to opt out entirely. */
  redaction?: RedactionConfig | RedactionUserConfig | null;
}

const LEVEL_PATTERNS: Record<string, RegExp> = {
  debug: /\b(debug|trace|verbose)\b/i,
  info: /\b(info|warn|warning|error|err|fatal|critical)\b/i,
  warn: /\b(warn|warning|error|err|fatal|critical)\b/i,
  error: /\b(error|err|fatal|critical|exception|panic)\b/i,
};

// any recognised level token. a line carrying none of these is "unlabelled" —
// most app logs (e.g. "server running at http://localhost:3007") are. the level
// filter must NOT drop unlabelled lines: we can't prove they're below the
// threshold, and silently dropping them made fleet_logs_recent return nothing
// for apps that log without level prefixes.
const ANY_LEVEL = /\b(debug|trace|verbose|info|warn|warning|error|err|fatal|critical)\b/i;

/**
 * Filter order is deliberate: level and grep run against the RAW text, then
 * redaction is applied, then the size cap.
 *
 * Why grep-on-raw: an operator grepping for a hostname, a customer email or an
 * account id still gets the lines they need — a grep against already-redacted
 * text would silently return nothing and read as "no such event", which is the
 * worse failure. The value is still redacted in the output they get back.
 *
 * The caveat, stated plainly: because matching happens pre-redaction, grepping
 * for a *literal secret value* confirms whether that value appears in the log
 * (by returning a line with a placeholder in it) even though the value itself
 * is never printed. That is an oracle, not a disclosure, and it is the price of
 * grep staying useful. Set `redaction.enabled` per app if you'd rather not have
 * either.
 *
 * Redaction runs BEFORE the maxBytes cap so truncation can never slice a secret
 * in half and leave the front of it visible.
 */
export function readContainerLogs(
  container: string,
  opts: LogReadOpts = {},
): { text: string; truncated: boolean; redacted?: Record<string, number> } {
  const args: string[] = ['logs', '--tail', String(opts.lines ?? 100)];
  if (opts.sinceMinutes) args.push('--since', `${opts.sinceMinutes}m`);
  args.push(container);
  const r = execSafe('docker', args);
  if (!r.ok) return { text: redactText(r.stderr, opts.redaction).text, truncated: false };
  let text = r.stdout;
  if (opts.level) {
    const pat = LEVEL_PATTERNS[opts.level];
    // keep blank lines, lines at/above the requested level, and unlabelled
    // lines; drop only lines that explicitly carry a lower level.
    text = text.split('\n')
      .filter(l => l.trim() === '' || pat.test(l) || !ANY_LEVEL.test(l))
      .join('\n');
  }
  if (opts.grep) {
    const g = opts.grep;
    text = text.split('\n').filter(l => l.includes(g)).join('\n');
  }
  const { text: redactedText, counts } = redactText(text, opts.redaction);
  text = redactedText;
  const cap = opts.maxBytes ?? 200_000;
  if (text.length > cap) {
    return { text: text.slice(0, cap), truncated: true, redacted: counts };
  }
  return { text, truncated: false, redacted: counts };
}
