/**
 * MOTD reporter: short summary of secret rotation health, intended for
 * /etc/update-motd.d/99-fleet-secrets to print on shell login.
 */

import { enumerateAllSecrets, type EnrichedSecret } from './secrets-metadata.js';
import type { Sensitivity } from './secrets-providers.js';

export interface SecretsMotdSummary {
  totalSecrets: number;
  staleCount: number;
  bySensitivity: Record<Sensitivity, number>;
  appsWithStale: string[];
  topStale: Array<{ app: string; name: string; ageDays: number; sensitivity: Sensitivity }>;
}

export function summariseSecrets(): SecretsMotdSummary {
  const all = enumerateAllSecrets();
  const stale = all.filter(s => s.stale);
  const bySensitivity: Record<Sensitivity, number> = { critical: 0, high: 0, medium: 0, low: 0 };
  for (const s of stale) {
    const sens = s.provider?.sensitivity ?? 'low';
    bySensitivity[sens]++;
  }
  const appsWithStale = Array.from(new Set(stale.map(s => s.app))).sort();

  const sensRank: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3 };
  const topStale = stale
    .slice()
    .sort((a, b) => {
      const sa = sensRank[a.provider?.sensitivity ?? 'low'];
      const sb = sensRank[b.provider?.sensitivity ?? 'low'];
      if (sa !== sb) return sa - sb;
      return (b.ageDays ?? 0) - (a.ageDays ?? 0);
    })
    .slice(0, 5)
    .map(s => ({
      app: s.app,
      name: s.name,
      ageDays: s.ageDays ?? 0,
      sensitivity: s.provider?.sensitivity ?? ('low' as Sensitivity),
    }));

  return {
    totalSecrets: all.length,
    staleCount: stale.length,
    bySensitivity,
    appsWithStale,
    topStale,
  };
}

export function formatSecretsMotd(summary: SecretsMotdSummary): string {
  const lines: string[] = [];
  lines.push('-- Fleet Secrets ' + '-'.repeat(40));

  if (summary.staleCount === 0) {
    lines.push(`  All ${summary.totalSecrets} secrets within rotation frequency`);
    lines.push('  Run: fleet secrets ages');
    return lines.join('\n');
  }

  const parts: string[] = [];
  if (summary.bySensitivity.critical > 0) parts.push(`${summary.bySensitivity.critical} critical`);
  if (summary.bySensitivity.high > 0) parts.push(`${summary.bySensitivity.high} high`);
  if (summary.bySensitivity.medium > 0) parts.push(`${summary.bySensitivity.medium} medium`);
  if (summary.bySensitivity.low > 0) parts.push(`${summary.bySensitivity.low} low`);

  lines.push(
    `  ${summary.staleCount} secrets need rotation (${parts.join(', ')}) across ${summary.appsWithStale.length} apps`,
  );

  for (const t of summary.topStale) {
    const prefix = t.sensitivity === 'critical' ? '!!' : t.sensitivity === 'high' ? ' !' : '  ';
    lines.push(`  ${prefix} ${t.app}: ${t.name} (${t.ageDays}d old)`);
  }

  lines.push('  Run: fleet secrets ages --stale-only');
  lines.push('  Rotate: fleet secrets rotate <app>');
  return lines.join('\n');
}

export function generateSecretsMotdScript(): string {
  return `#!/bin/bash
# fleet secrets motd — auto-generated by 'fleet secrets motd-init'
# shows secret rotation health summary on shell login
/usr/local/bin/fleet secrets ages --motd 2>/dev/null || true
`;
}
